# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Jacob
tagline:             Jacob's blogs
description:         '明天是你剩余人生的第一天'
url:                 /
baseurl:             /
paginate:            8

# About/contact
author:
  name:              Jacob Yan
  github:            Jacob110
  disqus:            gansteed

# Custom vars
#saying:              'Stand on the shoulders of giants, observing details of the world.'

# redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]
